"""Unit tests for the pure Lavalink config renderer."""

from __future__ import annotations

import yaml
from config_renderer.model import LavalinkCredentials, LavalinkSettings
from config_renderer.renderer import (
    YOUTUBE_CLIENTS,
    build_config,
    render_yaml,
)


def _full_creds() -> LavalinkCredentials:
    return LavalinkCredentials(
        spotify_client_id="sid",
        spotify_client_secret="ssec",
        tidal_token="ttok",
        tidal_client_id="tcid",
        tidal_client_secret="tsec",
        ytcipher_token="yct",
        youtube_oauth_refresh_token="rt",
        youtube_pot_token="pot",
        youtube_pot_visitor_data="vd",
    )


def test_youtube_client_cascade_preserved() -> None:
    config = build_config(_full_creds(), LavalinkSettings())
    clients = config["plugins"]["youtube"]["clients"]
    assert clients == ["TV", "TVHTML5_SIMPLY", "ANDROID_VR", "MUSIC", "WEB"]
    assert clients == list(YOUTUBE_CLIENTS)


def test_music_client_options_playback_disabled() -> None:
    config = build_config(_full_creds(), LavalinkSettings())
    music = config["plugins"]["youtube"]["clientOptions"]["MUSIC"]
    assert music == {"playback": False, "videoLoading": False}


def test_lavasrc_provider_order_soundcloud_first() -> None:
    config = build_config(_full_creds(), LavalinkSettings())
    providers = config["plugins"]["lavasrc"]["providers"]
    assert providers[0] == "scsearch:%QUERY%"
    assert 'ytsearch:"%ISRC%"' in providers
    assert "ytsearch:%QUERY%" in providers


def test_sources_enabled_when_credentials_present() -> None:
    config = build_config(_full_creds(), LavalinkSettings())
    lavasrc = config["plugins"]["lavasrc"]["sources"]
    assert lavasrc["spotify"] is True
    assert lavasrc["tidal"] is True
    assert lavasrc["youtube"] is True
    assert config["plugins"]["youtube"]["oauth"]["enabled"] is True


def test_sources_disabled_when_credentials_absent() -> None:
    config = build_config(LavalinkCredentials(), LavalinkSettings())
    lavasrc = config["plugins"]["lavasrc"]["sources"]
    assert lavasrc["spotify"] is False
    assert lavasrc["tidal"] is False
    # Tidal token still non-empty placeholder to avoid lavasrc crash.
    assert config["plugins"]["lavasrc"]["tidal"]["token"] == "disabled"
    assert config["plugins"]["youtube"]["oauth"]["enabled"] is False
    assert config["sources"]["spotify"]["enabled"] is False


def test_tidal_enabled_with_token_only() -> None:
    creds = LavalinkCredentials(tidal_token="realtoken")
    config = build_config(creds, LavalinkSettings())
    assert config["plugins"]["lavasrc"]["sources"]["tidal"] is True
    assert config["plugins"]["lavasrc"]["tidal"]["token"] == "realtoken"


def test_tidal_none_token_treated_as_disabled() -> None:
    creds = LavalinkCredentials(tidal_token="none")
    config = build_config(creds, LavalinkSettings())
    assert config["plugins"]["lavasrc"]["sources"]["tidal"] is False


def test_server_and_port_settings_applied() -> None:
    settings = LavalinkSettings(port=2444, server_password="secret")
    config = build_config(_full_creds(), settings)
    assert config["lavalink"]["server"]["port"] == 2444
    assert config["lavalink"]["server"]["password"] == "secret"
    assert config["server"]["port"] == 2444
    assert config["lavalink"]["server"]["sources"]["youtube"] is False


def test_render_yaml_is_parseable_and_headered() -> None:
    text = render_yaml(_full_creds(), LavalinkSettings())
    assert text.startswith("# Auto-generated by config-renderer")
    parsed = yaml.safe_load(text)
    assert parsed["plugins"]["youtube"]["clients"][0] == "TV"
    assert parsed["lavalink"]["server"]["port"] == 2333


def test_no_sqlite_reference_in_output() -> None:
    text = render_yaml(_full_creds(), LavalinkSettings()).lower()
    assert "sqlite" not in text
