apiVersion: v1
kind: Service
metadata:
  name: lavalink-pool
  namespace: hellodj-service
  labels:
    app.kubernetes.io/name: hellodj-lavalink
    app.kubernetes.io/component: lavalink
    app.kubernetes.io/part-of: hellodj
spec:
  clusterIP: None  # headless for direct pod addressing
  ports:
    - port: 2333
      targetPort: lavalink
      name: lavalink
      protocol: TCP
  selector:
    app.kubernetes.io/name: hellodj-lavalink
