apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hellodj-service

resources:
  - namespace.yaml
  - configmap.yaml
  - bot-configmap.yaml
  - youtube-secret.yaml
  - yt-cipher-secret.yaml
  - yt-cipher-deployment.yaml
  - yt-cipher-service.yaml
  - potoken-server-deployment.yaml
  - potoken-server-service.yaml
  - pvc.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
  - models-nfs-pv.yaml
  - models-pvc.yaml
  - backups-nfs-pv.yaml
  - backups-pvc.yaml
  - service.yaml
  - deployment.yaml
  - web-ui-service.yaml
  - web-ui-deployment.yaml
  - ingress.yaml

# Image tags
images:
  - name: registry.celestium.life/hellodj/bot
    newTag: sync-v3-2026-08-21
  - name: registry.celestium.life/hellodj/web-ui
    newTag: latest
  - name: registry.celestium.life/hellodj/tidal-stream
    newTag: latest
  - name: registry.celestium.life/hellodj/spotify-stream
    newTag: latest
