apiVersion: v1
kind: PersistentVolume
metadata:
  name: hellodj-models-nfs-pv
  namespace: hellodj-service
  labels:
    app.kubernetes.io/instance: hellodj
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: hellodj
    app.kubernetes.io/component: models
    helm.sh/chart: hellodj-0.1.0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - vers=4.1
  nfs:
    server: 192.168.42.8
    path: /volume1/Kubernetes/HelloDJ/models
    readOnly: false
