apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hellodj-config-pvc
  namespace: hellodj-service
  labels:
    app.kubernetes.io/instance: hellodj
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: hellodj
    app.kubernetes.io/component: config-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
  volumeName: hellodj-config-nfs-pv
