apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hellodj-data-pvc
  namespace: hellodj-service
  labels:
    app.kubernetes.io/instance: hellodj
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: hellodj
    app.kubernetes.io/component: data
    helm.sh/chart: hellodj-0.1.0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
