{
  description = ''
    HelloDJ playback-orchestrator component — routing, classification, content
    filtering, user bans, unified queue/session persistence (single writer to
    hellodj-session). Nix-built OCI image, NO Ubuntu/Debian base (R5.1/5.2/5.3).

    DynamoDB/DAX access via IAM (IRSA). No static credentials baked in (R6.1).
  '';

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachSystem [ "aarch64-linux" "x86_64-linux" ] (system:
      let
        pkgs = import nixpkgs { inherit system; };

        python = pkgs.python314;

        pythonDeps = ps: with ps; [
          boto3
          botocore
          # Envelope-decryption for the token-refresh watchdog: token_crypto
          # (AES-GCM via `cryptography`) is imported transitively by the shared
          # SourceCredentialService the watchdog reuses to decrypt/refresh
          # source credentials (unified-oauth-and-token-watchdog Task 8).
          cryptography
        ];

        pythonEnv = python.withPackages pythonDeps;

        # Reproducible source: strip transient files (__pycache__/*.pyc/*.pyo,
        # .git) so the derivation input hash depends ONLY on real source
        # content. CI-generated bytecode otherwise makes the -src hash (and the
        # whole image closure) differ every run, so the S3 cache never hits.
        filteredSrc = pkgs.lib.cleanSourceWith {
          src = ./.;
          filter = path: _type:
            let base = baseNameOf path;
            in base != "__pycache__"
              && base != ".git"
              && !pkgs.lib.hasSuffix ".pyc" base
              && !pkgs.lib.hasSuffix ".pyo" base;
        };

        appSrc = pkgs.runCommand "hellodj-playback-orchestrator-src" { src = filteredSrc; } ''
          mkdir -p $out/app
          cp -r $src/playback_orchestrator $out/app/playback_orchestrator 2>/dev/null || true
          find $src -maxdepth 1 -name '*.py' -exec cp {} $out/app/ \;
          # Shared platform logic package (copied into source tree by pipeline)
          if [ -d "$src/hellodj_platform_logic" ]; then
            cp -r "$src/hellodj_platform_logic" $out/app/hellodj_platform_logic
          fi
          # Shared, dependency-light credential store the token-refresh watchdog
          # reuses. It is authored as a web-ui module but imports only
          # hellodj_platform_logic, so it is safe to place beside the app here
          # (the pipeline copies it into the source tree next to the shared
          # package). One identity/store spans web-ui, watchdog, and bot.
          if [ -f "$src/source_credential_service.py" ]; then
            cp "$src/source_credential_service.py" $out/app/source_credential_service.py
          fi
        '';

        image = pkgs.dockerTools.buildLayeredImage {
          name = "hellodj-playback-orchestrator";
          tag = "nix";

          contents = [ pythonEnv pkgs.cacert pkgs.coreutils ];

          extraCommands = ''
            cp -r ${appSrc}/app opt-app
          '';

          config = {
            WorkingDir = "/opt-app";
            ExposedPorts = { "8080/tcp" = { }; };
            Env = [
              "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
              "PYTHONUNBUFFERED=1"
            ];
            Entrypoint = [
              "${pythonEnv}/bin/python"
              "-m" "playback_orchestrator"
            ];
          };
        };
      in
      {
        packages = {
          default = image;
          image = image;
        };
        checks = { image-builds = image; };
      });
}
