"""Property test for the hybrid GPU spin-up / scale-to-zero controller (task 5.6).

Property 15 (design "The hybrid gas/electric transcode model"): *for any*
sequence of transcode-demand readings with defined ``spin_up_threshold``,
``spin_down_threshold`` (where ``spin_down_threshold < spin_up_threshold``) and
sustained-duration windows, the hybrid transcode controller
(:mod:`hellodj_platform_logic.hybrid_gpu`) SHALL:

* keep the CPU (electric) path serving at all times -- every
  :class:`ControllerStatus` returned by :func:`advance`/:func:`run` has
  ``cpu_serving`` True, so no interactive request is unserved, even mid
  spin-up (R3.12, R3.13);
* prefer the GPU only while the GPU node is ``Ready`` -- ``gpu_preferred`` is
  True *iff* the state is :attr:`HybridGpuState.HYBRID_GPU`;
* leave ``ELECTRIC_ONLY`` (to ``ENGINE_STARTING``) only after demand has been
  strictly above ``spin_up_threshold`` for at least ``spin_up_window_seconds``
  (spin-up timing, R3.9/R3.10);
* leave ``COASTING`` back to ``ELECTRIC_ONLY`` only after demand has been
  strictly below ``spin_down_threshold`` for at least
  ``spin_down_window_seconds`` and the GPU node is no longer Ready
  (scale-to-zero timing);
* move ``ENGINE_STARTING`` -> ``HYBRID_GPU`` only once ``gpu_ready``; and
* always report one of the four valid :class:`HybridGpuState` values.

The controller also rejects invalid thresholds
(``spin_down_threshold >= spin_up_threshold``) with :class:`HybridGpuError`.

The controller is pure, so the property is exercised directly by folding
:func:`advance` over Hypothesis-generated demand-sample sequences and by
driving :func:`run`. Thresholds are generated by drawing
``spin_down_threshold`` first and then ``spin_up_threshold`` strictly above it,
with non-negative sustained windows; demand samples use non-negative durations.

Feature: aws-saas-replatform, Property 15

Validates: Requirements 3.2, 3.3, 3.9, 3.10, 3.12, 3.13
"""

from __future__ import annotations

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from hellodj_platform_logic.hybrid_gpu import (
    ControllerStatus,
    DemandSample,
    HybridGpuError,
    advance,
    initial_status,
    run,
)
from hellodj_platform_logic.types import HybridGpuState, HybridGpuThresholds

_VALID_STATES = frozenset(HybridGpuState)

# Bounded, finite values keep the generated demand/threshold space sensible.
_level = st.floats(
    min_value=-1000.0,
    max_value=1000.0,
    allow_nan=False,
    allow_infinity=False,
)
_window = st.floats(
    min_value=0.0,
    max_value=1000.0,
    allow_nan=False,
    allow_infinity=False,
)
_duration = st.floats(
    min_value=0.0,
    max_value=1000.0,
    allow_nan=False,
    allow_infinity=False,
)


@st.composite
def _valid_thresholds(draw: st.DrawFn) -> HybridGpuThresholds:
    """Draw thresholds with ``spin_down_threshold`` < ``spin_up_threshold``.

    We draw ``spin_down_threshold`` first, then ``spin_up_threshold`` strictly
    greater than it (via a positive gap), so the hysteresis requirement always
    holds. Sustained windows are non-negative.
    """
    spin_down = draw(_level)
    gap = draw(
        st.floats(
            min_value=0.001,
            max_value=2000.0,
            allow_nan=False,
            allow_infinity=False,
        )
    )
    spin_up = spin_down + gap
    return HybridGpuThresholds(
        spin_up_threshold=spin_up,
        spin_down_threshold=spin_down,
        spin_up_window_seconds=draw(_window),
        spin_down_window_seconds=draw(_window),
    )


@st.composite
def _demand_samples(draw: st.DrawFn) -> list[DemandSample]:
    """Draw a sequence of demand samples with non-negative durations."""
    return draw(
        st.lists(
            st.builds(
                DemandSample,
                demand=_level,
                duration_seconds=_duration,
            ),
            min_size=0,
            max_size=40,
        )
    )


def _assert_status_invariants(status: ControllerStatus) -> None:
    """Every returned status keeps CPU serving, valid state, gpu iff HYBRID."""
    # returned state is always one of the four valid states.
    assert status.state in _VALID_STATES
    # CPU always serves: no interactive request is unserved, even mid spin-up.
    assert status.cpu_serving is True
    # GPU is preferred ONLY in HYBRID_GPU (GPU preferred only while Ready).
    assert status.gpu_preferred == (status.state is HybridGpuState.HYBRID_GPU)


@settings(max_examples=300)
@given(samples=_demand_samples(), thresholds=_valid_thresholds())
def test_run_holds_core_invariants(
    samples: list[DemandSample], thresholds: HybridGpuThresholds
) -> None:
    """Driving ``run`` keeps CPU serving, valid states, gpu-iff-HYBRID.

    Feature: aws-saas-replatform, Property 15

    Validates: Requirements 3.2, 3.3, 3.10, 3.12, 3.13
    """
    final = run(samples, thresholds)
    _assert_status_invariants(final)


@settings(max_examples=300)
@given(
    samples=_demand_samples(),
    thresholds=_valid_thresholds(),
    gpu_ready=st.booleans(),
)
def test_advance_step_invariants(
    samples: list[DemandSample],
    thresholds: HybridGpuThresholds,
    gpu_ready: bool,
) -> None:
    """Every intermediate ``advance`` status holds the core invariants.

    We fold ``advance`` manually with a fixed ``gpu_ready`` signal and assert
    the invariants after each step (not just the final status), so CPU-always-
    serves and gpu-preferred-iff-HYBRID hold at every point of the run.

    Feature: aws-saas-replatform, Property 15

    Validates: Requirements 3.2, 3.3, 3.10, 3.12, 3.13
    """
    status = initial_status()
    _assert_status_invariants(status)
    for sample in samples:
        status = advance(status, sample, thresholds, gpu_ready=gpu_ready)
        _assert_status_invariants(status)


@settings(max_examples=300)
@given(
    sample=st.builds(DemandSample, demand=_level, duration_seconds=_duration),
    thresholds=_valid_thresholds(),
    gpu_ready=st.booleans(),
)
def test_spin_up_timing_from_electric_only(
    sample: DemandSample,
    thresholds: HybridGpuThresholds,
    gpu_ready: bool,
) -> None:
    """ELECTRIC_ONLY leaves only once the above-threshold window is met.

    Starting from ELECTRIC_ONLY (both accumulators at zero), a single sample
    can only move to ENGINE_STARTING when the demand it carries, if strictly
    above ``spin_up_threshold``, accrues enough duration to meet
    ``spin_up_window_seconds``; otherwise the controller stays in
    ELECTRIC_ONLY. (``gpu_ready`` is irrelevant out of ELECTRIC_ONLY.)

    Feature: aws-saas-replatform, Property 15

    Validates: Requirements 3.9, 3.10
    """
    status = initial_status()
    nxt = advance(status, sample, thresholds, gpu_ready=gpu_ready)

    # Mirror the controller: from ELECTRIC_ONLY (above_seconds == 0) a sample
    # strictly above spin_up accrues its duration into above_seconds, anything
    # else resets it to 0; the spin-up window is met when that accrued duration
    # is >= spin_up_window_seconds (so a zero-length window is trivially met).
    above_seconds = (
        sample.duration_seconds
        if sample.demand > thresholds.spin_up_threshold
        else 0.0
    )
    spin_up_met = above_seconds >= thresholds.spin_up_window_seconds
    if spin_up_met:
        assert nxt.state is HybridGpuState.ENGINE_STARTING
    else:
        assert nxt.state is HybridGpuState.ELECTRIC_ONLY


@settings(max_examples=300)
@given(thresholds=_valid_thresholds(), gpu_ready=st.booleans())
def test_engine_starting_to_hybrid_requires_gpu_ready(
    thresholds: HybridGpuThresholds, gpu_ready: bool
) -> None:
    """ENGINE_STARTING -> HYBRID_GPU happens iff the GPU node is Ready.

    From an ENGINE_STARTING status, advancing with any sample reaches
    HYBRID_GPU exactly when ``gpu_ready`` is True; when the node is not Ready it
    stays ENGINE_STARTING (the CPU keeps serving through the boot window).

    Feature: aws-saas-replatform, Property 15

    Validates: Requirements 3.9, 3.10, 3.12, 3.13
    """
    starting = ControllerStatus(
        state=HybridGpuState.ENGINE_STARTING,
        cpu_serving=True,
        gpu_preferred=False,
        above_seconds=0.0,
        below_seconds=0.0,
    )
    # A neutral sample in the hysteresis band avoids confounding accumulation.
    band_demand = (
        thresholds.spin_up_threshold + thresholds.spin_down_threshold
    ) / 2.0
    sample = DemandSample(demand=band_demand, duration_seconds=1.0)
    nxt = advance(starting, sample, thresholds, gpu_ready=gpu_ready)

    if gpu_ready:
        assert nxt.state is HybridGpuState.HYBRID_GPU
    else:
        assert nxt.state is HybridGpuState.ENGINE_STARTING
    _assert_status_invariants(nxt)


@settings(max_examples=300)
@given(
    sample=st.builds(DemandSample, demand=_level, duration_seconds=_duration),
    thresholds=_valid_thresholds(),
    gpu_ready=st.booleans(),
)
def test_scale_to_zero_timing_from_coasting(
    sample: DemandSample,
    thresholds: HybridGpuThresholds,
    gpu_ready: bool,
) -> None:
    """COASTING returns to ELECTRIC_ONLY only once the below window is met and not Ready.

    From a COASTING status (accumulators zeroed), a single sample returns to
    ELECTRIC_ONLY only when a strictly-below-``spin_down_threshold`` demand
    accrues enough duration to meet ``spin_down_window_seconds`` *and* the GPU
    node is no longer Ready. If instead a strictly-above-``spin_up_threshold``
    demand meets the spin-up window it rejoins HYBRID_GPU; otherwise it keeps
    COASTING.

    Feature: aws-saas-replatform, Property 15

    Validates: Requirements 3.9, 3.10, 3.12, 3.13
    """
    coasting = ControllerStatus(
        state=HybridGpuState.COASTING,
        cpu_serving=True,
        gpu_preferred=False,
        above_seconds=0.0,
        below_seconds=0.0,
    )
    nxt = advance(coasting, sample, thresholds, gpu_ready=gpu_ready)

    # Mirror the controller's accumulate step from zeroed accumulators: a
    # demand strictly above spin_up accrues into above_seconds (below reset),
    # strictly below spin_down accrues into below_seconds (above reset), and a
    # band demand resets both. The window is met when the accrued duration is
    # >= the corresponding window (so a zero-length window is trivially met).
    if sample.demand > thresholds.spin_up_threshold:
        above_seconds, below_seconds = sample.duration_seconds, 0.0
    elif sample.demand < thresholds.spin_down_threshold:
        above_seconds, below_seconds = 0.0, sample.duration_seconds
    else:
        above_seconds, below_seconds = 0.0, 0.0
    spin_up_met = above_seconds >= thresholds.spin_up_window_seconds
    spin_down_met = below_seconds >= thresholds.spin_down_window_seconds

    if spin_up_met:
        # Demand rose again before scale-to-zero completed.
        assert nxt.state is HybridGpuState.HYBRID_GPU
    elif spin_down_met and not gpu_ready:
        # Jobs drained back to CPU and the GPU node has scaled to zero.
        assert nxt.state is HybridGpuState.ELECTRIC_ONLY
    else:
        assert nxt.state is HybridGpuState.COASTING
    _assert_status_invariants(nxt)


@settings(max_examples=200)
@given(
    spin_up=_level,
    delta=st.floats(
        min_value=0.0, max_value=2000.0, allow_nan=False, allow_infinity=False
    ),
    up_window=_window,
    down_window=_window,
    sample=st.builds(DemandSample, demand=_level, duration_seconds=_duration),
)
def test_invalid_thresholds_raise(
    spin_up: float,
    delta: float,
    up_window: float,
    down_window: float,
    sample: DemandSample,
) -> None:
    """Thresholds with spin_down >= spin_up raise HybridGpuError.

    Feature: aws-saas-replatform, Property 15

    Validates: Requirements 3.9, 3.10
    """
    # spin_down_threshold >= spin_up_threshold violates hysteresis.
    spin_down = spin_up + delta
    bad = HybridGpuThresholds(
        spin_up_threshold=spin_up,
        spin_down_threshold=spin_down,
        spin_up_window_seconds=up_window,
        spin_down_window_seconds=down_window,
    )
    with pytest.raises(HybridGpuError):
        advance(initial_status(), sample, bad)
    with pytest.raises(HybridGpuError):
        run([sample], bad)
