apiVersion: v1
kind: Namespace
metadata:
  name: redis-service
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: namespace
