apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-service
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
