#!/usr/bin/env python3
"""HelloDJ — Lavalink config renderer.

Reads credentials from the encrypted SQLite store and renders a complete
application.yml for Lavalink. Runs as an init container before Lavalink starts.

Usage:
    HELLODJ_DB_KEY=<key> python render_lavalink_config.py /output/application.yml
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault("DATA_DIR", "/app/data")

from credentials import creds


def render() -> str:
    """Render the full Lavalink application.yml from the credential store."""
    spotify_id = creds.get("spotify.client_id", "")
    spotify_secret = creds.get("spotify.client_secret", "")
    tidal_token = creds.get("tidal.access_token") or creds.get("tidal.api_token") or "none"
    tidal_client_id = creds.get("tidal.td_client_id") or creds.get("tidal.client_id") or ""
    tidal_client_secret = creds.get("tidal.td_client_secret") or creds.get("tidal.client_secret") or ""
    tidal_country = creds.get("tidal.country_code", "US")
    tidal_limit = creds.get("tidal.search_limit", "6")
    ytcipher_token = creds.get("ytcipher.api_token", "")
    yt_refresh_token = creds.get("youtube.oauth_refresh_token") or creds.get("youtube.refresh_token") or ""
    yt_pot_token = creds.get("youtube.pot_token", "")
    yt_visitor_data = creds.get("youtube.pot_visitor_data", "")

    # Tidal source enabled if we have either client credentials OR a real token
    has_tidal_creds = bool(tidal_client_id and tidal_client_secret)
    has_tidal_token = bool(tidal_token and tidal_token not in ("none", ""))
    tidal_enabled = "true" if (has_tidal_creds or has_tidal_token) else "false"
    # If tidal disabled, still need a non-empty placeholder to avoid lavasrc crash
    tidal_token_val = tidal_token if has_tidal_token else "disabled"

    # Spotify enabled only if credentials exist
    spotify_enabled = "true" if (spotify_id and spotify_secret) else "false"

    # YouTube OAuth enabled if we have a refresh token
    yt_oauth_enabled = "true" if yt_refresh_token else "false"

    return f"""# Auto-generated by render_lavalink_config.py — DO NOT EDIT
# Credentials sourced from encrypted SQLite store.

lavalink:
  server:
    host: "0.0.0.0"
    port: 2333
    password: "youshallnotpass"
    pluginsDir: "./plugins"
    sources:
      youtube: false
  buffer:
    period: 500
    periodMilliseconds: 500
  limits:
    memory: 0
    cpu: 0

  plugins:
    # All plugins baked into Lavalink image — no maven downloads needed

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TV
      - TVHTML5_SIMPLY
      - ANDROID_VR
      - MUSIC
      - WEB
    clientOptions:
      MUSIC:
        playback: false
        videoLoading: false
    oauth:
      enabled: {yt_oauth_enabled}
      refreshToken: "{yt_refresh_token}"
    pot:
      token: "{yt_pot_token}"
      visitorData: "{yt_visitor_data}"
    remoteCipher:
      url: "http://yt-cipher.hellodj-service.svc.cluster.local:8001"
      password: "{ytcipher_token}"
      userAgent: "hellodj"
  lavasrc:
    providers:
      - "scsearch:%QUERY%"
      - "ytsearch:\\"%ISRC%\\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: {spotify_enabled}
      tidal: {tidal_enabled}
      youtube: true
    tidal:
      countryCode: "{tidal_country}"
      searchLimit: {tidal_limit}
      clientId: "{tidal_client_id}"
      clientSecret: "{tidal_client_secret}"
      token: "{tidal_token_val}"
    spotify:
      clientId: "{spotify_id}"
      clientSecret: "{spotify_secret}"
      countryCode: "US"
      playlistLoadLimit: 6
      albumLoadLimit: 6
      resolveArtistsInSearch: false

sources:
  youtube:
    enabled: true
  youtubemusic:
    enabled: true
  soundcloud:
    enabled: true
  spotify:
    enabled: {spotify_enabled}

filters:
  enabled: true
  volume:
    enabled: true
  equalizer:
    enabled: true
  karaoke:
    enabled: true
  timescale:
    enabled: true
  tremolo:
    enabled: true
  vibrato:
    enabled: true
  distortion:
    enabled: true
  rotation:
    enabled: true
  lowPass:
    enabled: true
  channelMix:
    enabled: true

server:
  port: 2333
"""


def main():
    if len(sys.argv) < 2:
        output_path = "/opt/Lavalink/application.yml"
    else:
        output_path = sys.argv[1]

    config = render()
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)
    print(f"Rendered Lavalink config to {output_path}")


if __name__ == "__main__":
    main()
